services:
  # Frontend
  frontend:
    build:
      context: ./frontend
    ports:
      - "${PORT_FRONTEND}:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
    depends_on:
      - gateway

  # API Gateway
  gateway:
    image: nginx:alpine
    volumes:
      - ./backend/gateway/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "${PORT_GATEWAY}:80"
    depends_on:
      auth-service:
        condition: service_started
      auction-service:
        condition: service_started
      bidding-service:
        condition: service_started

  # Database
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "${PORT_DB}:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p${DB_ROOT_PASSWORD} --silent" ]
      interval: 5s
      timeout: 3s
      retries: 20

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "${PORT_PHPMYADMIN}:80"
    depends_on:
      - db

  # Microservices
  auth-service:
    build:
      context: ./backend/auth-service
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
      - DB_NAME=${DB_DATABASE}
      - PORT=${PORT_AUTH_SERVICE}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - BACKEND_URL=${BACKEND_URL}
    volumes:
      - ./backend/auth-service:/app
      - /app/node_modules
      - ./backend/auth-service/uploads:/app/uploads
    # Usamos npx para evitar errores de permisos con nodemon
    command: npx nodemon index.js
    depends_on:
      db:
        condition: service_healthy

  auction-service:
    build:
      context: ./backend/auction-service
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
      - DB_NAME=${DB_DATABASE}
      - PORT=${PORT_AUCTION_SERVICE}
      - SERVICE_PREFIX=/auction
    volumes:
      - ./backend/auction-service:/app
      - /app/node_modules
      - ./backend/auction-service/uploads:/app/uploads
    command: npx nodemon index.js
    depends_on:
      db:
        condition: service_healthy

  bidding-service:
    build:
      context: ./backend/bidding-service
    environment:
      - PORT=${PORT_BIDDING_SERVICE}
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
      - DB_NAME=${DB_DATABASE}
    volumes:
      - ./backend/bidding-service:/app
      - /app/node_modules
    command: npx nodemon index.js
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
