import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

const translations = {
    en: {
        nav: {
            live: 'Live Auctions',
            upcoming: 'Upcoming',
            auctioneers: 'Auctioneers',
            searchPlaceholder: 'Search sneakers, art, cards...',
            goLive: 'Go Live',
            login: 'Login',
            logout: 'Logout',
            profile: 'My Profile',
            notifications: 'Notifications',
            home: 'Home',
            explore: 'Explore',
            dashboard: 'Dashboard',
            signin: 'Sign in',
            getstarted: 'Get started',
            newauction: 'New auction',
            addmoney: 'Add Money',
            signout: 'Sign out'
        },
        home: {
            liveBadge: 'Live auctions happening right now',
            heroTitle1: 'Bid smarter, ',
            heroTitle2: 'win live.',
            heroSubtitle: 'Watch sellers showcase their items live and place real-time bids. The most thrilling auction experience on the web.',
            exploreBtn: 'Explore auctions',
            sellBtn: 'Sell something',
            stats: {
                total: 'Total auctions',
                live: 'Live right now',
                traded: 'Traded this week',
                satisfaction: 'Seller satisfaction'
            }
        },
        liveGrid: {
            rep: { new: "New", beginner: "Beginner", regular: "Regular", reliable: "Reliable", outstanding: "Outstanding", top: "Top" },
            live: 'LIVE',
            currentBid: 'Current bid',
            seller: 'Seller',
            title: 'Live now',
            liveCount: 'live',
            seeAll: 'See all',
            error: 'Unable to load live auctions',
            emptyTitle: 'No live auctions at the moment',
            emptySub: 'Check back soon or start your own!',
            startBtn: 'Start an auction'
        },
        activeListings: {
            title: 'All auctions',
            browseAll: 'Browse all',
            error: 'Failed to load auctions. Is the backend running?',
            emptyTitle: 'No auctions yet',
            emptySub: 'Be the first to create one!',
            createBtn: 'Create auction',
            colItem: 'Item',
            colSeller: 'Seller',
            colStatus: 'Status',
            colBid: 'Bid',
            statusLive: 'Live',
            actionJoin: 'Join',
            actionView: 'View'
        },
        profile: {
            title: 'My Profile',
            stats: 'My Stats',
            activity: 'Recent Activity',
            edit: 'Edit Profile'
        },
        auctioneers: {
            title: 'Top Auctioneers',
            subtitle: 'Discover the best sellers on BidLive.'
        },
        login: {
            liveBadge: 'Live auctions happening now',
            title1: 'The world\'s most',
            title2: 'thrilling',
            title3: ' auction',
            title4: 'platform.',
            subtitle: 'Watch, bid, and win in real-time. Thousands of items go live every day.',
            stat1: 'Active auctions',
            stat2: 'Live now',
            stat3: 'Satisfaction',
            welcome: 'Welcome back',
            welcomeSub: 'Sign in to continue bidding',
            email: 'Email address',
            emailPlaceholder: 'you@example.com',
            pass: 'Password',
            forgotPass: 'Forgot password?',
            passPlaceholder: 'Your password',
            btnSign: 'Sign in',
            or: 'Or continue with',
            noAccount: 'Don\'t have an account?',
            createOne: 'Create one'
        },
        register: {
            title1: 'Join the world\'s',
            title2: 'fastest growing',
            title3: 'auction platform.',
            subtitle: 'Buy, sell and bid on unique items — all in real-time. Create your account in seconds.',
            stat1: 'Account creation',
            stat2: 'Bidding experience',
            stat3: 'Transactions',
            create: 'Create your account',
            createSub: 'Start bidding in seconds.',
            username: 'Username',
            userPlaceholder: 'coolbidder99',
            email: 'Email address',
            emailPlaceholder: 'you@example.com',
            pass: 'Password',
            passPlaceholder: 'Min. 6 characters',
            confirm: 'Confirm password',
            confirmPlaceholder: 'Repeat your password',
            passMismatch: 'Passwords don\'t match',
            btnCreate: 'Create account',
            or: 'Or continue with',
            hasAccount: 'Already have an account?',
            signIn: 'Sign in'
        },
        search: {
            title1: 'Explore ',
            title2: 'auctions',
            searchPlaceholder: 'Search by item name...',
            searchBtn: 'Search',
            allBtn: 'All',
            searching: 'Searching...',
            found: 'auctions found',
            foundSingle: 'auction found',
            inCategory: 'in',
            forQuery: 'for',
            clearAll: 'Clear all filters',
            error: 'Unable to load auctions. Please try again.',
            noTitle: 'No auctions found',
            noSubFiltered: 'No results for the current filters.',
            noSubEmpty: 'Be the first to create an auction!',
            clearBtn: 'Clear filters',
            createBtn: 'Create auction'
        },
        create: {
            title: 'New auction',
            subtitle: 'Fill in the details and go live instantly.',
            photo: 'Item photo',
            uploadText: 'Click to upload or drag & drop',
            uploadSub: 'PNG, JPG or WEBP — max 5MB',
            removeImg: 'Remove image',
            itemTitle: 'Title *',
            titlePlaceholder: 'e.g. Vintage Rolex Submariner 1965',
            desc: 'Description',
            descPlaceholder: 'Describe your item — condition, authenticity, history...',
            category: 'Category',
            price: 'Starting price *',
            launchBtn: 'Launch auction live',
            launchSub: 'Your auction will start immediately as a live stream'
        },
        dashboard: {
            title: 'Dashboard',
            welcome: 'Welcome back,',
            newBtn: 'New auction',
            totalAuctions: 'Total auctions',
            liveNow: 'Live now',
            totalValue: 'Total value',
            myAuctions: 'My Auctions',
            colItem: 'Item',
            colStatus: 'Status',
            colStarting: 'Starting/Current',
            colFinal: 'Final Price',
            colActions: 'Actions',
            noActive: 'No active auctions',
            createFirst: 'Create your first auction',
            badgeLive: 'Live',
            badgeEnded: 'Ended',
            badgeNotLive: 'Not Live',
            btnEnterLive: 'Enter Live',
            btnGoLive: 'Go Live',
            historyTitle: 'Auction History (Ended)',
            noEnded: 'No ended auctions yet',
            badgeCompleted: 'Completed',
            btnClosed: 'Closed'
        }
    },
    es: {
        nav: {
            live: 'En Vivo',
            upcoming: 'Próximos',
            auctioneers: 'Subastadores',
            searchPlaceholder: 'Buscar zapatillas... ',
            goLive: 'Crear Subasta',
            login: 'Iniciar Sesión',
            logout: 'Cerrar Sesión',
            profile: 'Mi Perfil',
            notifications: 'Notificaciones',
            home: 'Inicio',
            explore: 'Explorar',
            dashboard: 'Dashboard',
            signin: 'Iniciar Sesión',
            getstarted: 'Comenzar',
            newauction: 'Nueva subasta',
            addmoney: 'Añadir Dinero',
            signout: 'Cerrar Sesión'
        },
        home: {
            liveBadge: 'Subastas en vivo ahora mismo',
            heroTitle1: 'Puja mejor, ',
            heroTitle2: 'gana en vivo.',
            heroSubtitle: 'Mira a los vendedores mostrar sus artículos en vivo y haz pujas en tiempo real. La experiencia más emocionante en la web.',
            exploreBtn: 'Explorar subastas',
            sellBtn: 'Vender algo',
            stats: {
                total: 'Subastas totales',
                live: 'En vivo ahora',
                traded: 'Vendido esta semana',
                satisfaction: 'Satisfacción del vendedor'
            }
        },
        liveGrid: {
            rep: { new: "Nuevo", beginner: "Principiante", regular: "Regular", reliable: "Confiable", outstanding: "Destacado", top: "Top" },
            live: 'EN VIVO',
            currentBid: 'Puja actual',
            seller: 'Vendedor',
            title: 'En vivo ahora',
            liveCount: 'en vivo',
            seeAll: 'Ver todas',
            error: 'No se pudieron cargar las subastas en vivo',
            emptyTitle: 'No hay subastas en vivo en este momento',
            emptySub: '¡Vuelve pronto o crea la tuya!',
            startBtn: 'Comenzar una subasta'
        },
        activeListings: {
            title: 'Todas las subastas',
            browseAll: 'Explorar todas',
            error: 'Error al cargar las subastas. ¿El backend está funcionando?',
            emptyTitle: 'No hay subastas aún',
            emptySub: '¡Sé el primero en crear una!',
            createBtn: 'Crear subasta',
            colItem: 'Artículo',
            colSeller: 'Vendedor',
            colStatus: 'Estado',
            colBid: 'Puja',
            statusLive: 'En vivo',
            actionJoin: 'Unirse',
            actionView: 'Ver'
        },
        profile: {
            title: 'Mi Perfil',
            stats: 'Mis Estadísticas',
            activity: 'Actividad Reciente',
            edit: 'Editar Perfil'
        },
        auctioneers: {
            title: 'Mejores Subastadores',
            subtitle: 'Descubre los mejores vendedores.'
        },
        login: {
            liveBadge: 'Subastas en vivo ahora',
            title1: 'La plataforma de subastas',
            title2: 'más emocionante',
            title3: '',
            title4: 'del mundo.',
            subtitle: 'Mira, puja y gana en tiempo real. Miles de artículos en vivo cada día.',
            stat1: 'Subastas activas',
            stat2: 'En vivo ahora',
            stat3: 'Satisfacción',
            welcome: 'Bienvenido de nuevo',
            welcomeSub: 'Inicia sesión para continuar pujando',
            email: 'Correo electrónico',
            emailPlaceholder: 'tu@ejemplo.com',
            pass: 'Contraseña',
            forgotPass: '¿Olvidaste tu contraseña?',
            passPlaceholder: 'Tu contraseña',
            btnSign: 'Iniciar sesión',
            or: 'O continuar con',
            noAccount: '¿No tienes una cuenta?',
            createOne: 'Crea una'
        },
        register: {
            title1: 'Únete a la plataforma de subastas',
            title2: 'de más rápido crecimiento',
            title3: '',
            subtitle: 'Compra, vende y puja por artículos únicos — en tiempo real. Crea tu cuenta en segundos.',
            stat1: 'Creación de cuenta',
            stat2: 'Experiencia de pujas',
            stat3: 'Transacciones',
            create: 'Crea tu cuenta',
            createSub: 'Empieza a pujar en segundos.',
            username: 'Nombre de usuario',
            userPlaceholder: 'usuario99',
            email: 'Correo electrónico',
            emailPlaceholder: 'tu@ejemplo.com',
            pass: 'Contraseña',
            passPlaceholder: 'Mín. 6 caracteres',
            confirm: 'Confirmar contraseña',
            confirmPlaceholder: 'Repite tu contraseña',
            passMismatch: 'Las contraseñas no coinciden',
            btnCreate: 'Crear cuenta',
            or: 'O continuar con',
            hasAccount: '¿Ya tienes una cuenta?',
            signIn: 'Inicia sesión'
        },
        search: {
            title1: 'Explorar ',
            title2: 'subastas',
            searchPlaceholder: 'Buscar por nombre...',
            searchBtn: 'Buscar',
            allBtn: 'Todas',
            searching: 'Buscando...',
            found: 'subastas encontradas',
            foundSingle: 'subasta encontrada',
            inCategory: 'en',
            forQuery: 'para',
            clearAll: 'Borrar filtros',
            error: 'No se pudieron cargar. Inténtalo de nuevo.',
            noTitle: 'No se encontraron subastas',
            noSubFiltered: 'No hay resultados para estos filtros.',
            noSubEmpty: '¡Sé el primero en crear una!',
            clearBtn: 'Borrar filtros',
            createBtn: 'Crear subasta'
        },
        create: {
            title: 'Nueva subasta',
            subtitle: 'Completa los detalles e inicia en vivo al instante.',
            photo: 'Foto del artículo',
            uploadText: 'Haz clic para subir o arrastra y suelta',
            uploadSub: 'PNG, JPG o WEBP — máx 5MB',
            removeImg: 'Quitar imagen',
            itemTitle: 'Título *',
            titlePlaceholder: 'ej. Rolex Submariner Vintage 1965',
            desc: 'Descripción',
            descPlaceholder: 'Describe tu artículo — estado, autenticidad, historia...',
            category: 'Categoría',
            price: 'Precio inicial *',
            launchBtn: 'Lanzar subasta en vivo',
            launchSub: 'Tu subasta comenzará inmediatamente como un directo'
        },
        dashboard: {
            title: 'Dashboard',
            welcome: 'Bienvenido/a de nuevo,',
            newBtn: 'Nueva subasta',
            totalAuctions: 'Subastas totales',
            liveNow: 'En vivo ahora',
            totalValue: 'Valor total',
            myAuctions: 'Mis subastas',
            colItem: 'Artículo',
            colStatus: 'Estado',
            colStarting: 'Inicial/Actual',
            colFinal: 'Precio final',
            colActions: 'Acciones',
            noActive: 'No hay subastas activas',
            createFirst: 'Crea tu primera subasta',
            badgeLive: 'En vivo',
            badgeEnded: 'Finalizada',
            badgeNotLive: 'Sin empezar',
            btnEnterLive: 'Entrar al Directo',
            btnGoLive: 'Iniciar Directo',
            historyTitle: 'Historial de Pujas (Finalizadas)',
            noEnded: 'No hay subastas finalizadas aún',
            badgeCompleted: 'Completada',
            btnClosed: 'Cerrada'
        }
    },
    ca: {
        nav: {
            live: 'En Directe',
            upcoming: 'Propers',
            auctioneers: 'Subhastadors',
            searchPlaceholder: 'Cerca sabatilles...',
            goLive: 'Crear Subhasta',
            login: 'Iniciar Sessió',
            logout: 'Tancar Sessió',
            profile: 'El Meu Perfil',
            notifications: 'Notificacions',
            home: 'Inici',
            explore: 'Explorar',
            dashboard: 'Tauler',
            signin: 'Iniciar Sessió',
            getstarted: 'Començar',
            newauction: 'Nova subhasta',
            addmoney: 'Afegir Diners',
            signout: 'Tancar Sessió'
        },
        home: {
            liveBadge: 'Subhastes en directe ara mateix',
            heroTitle1: 'Puja millor, ',
            heroTitle2: 'guanya en directe.',
            heroSubtitle: 'Mira als venedors mostrar els seus articles en directe i fes pujes en temps real. L\'experiència més emocionant a la web.',
            exploreBtn: 'Explorar subhastes',
            sellBtn: 'Vendre alguna cosa',
            stats: {
                total: 'Subhastes totals',
                live: 'En directe ara',
                traded: 'Venut aquesta setmana',
                satisfaction: 'Satisfacció del venedor'
            }
        },
        liveGrid: {
            rep: { new: "Nou", beginner: "Principiant", regular: "Regular", reliable: "Confiable", outstanding: "Destacat", top: "Top" },
            live: 'EN DIRECTE',
            currentBid: 'Puja actual',
            seller: 'Venedor',
            title: 'En directe ara',
            liveCount: 'en directe',
            seeAll: 'Veure totes',
            error: 'No s\'han pogut carregar les subhastes en directe',
            emptyTitle: 'No hi ha subhastes en directe en aquest moment',
            emptySub: 'Torna aviat o crea la teva!',
            startBtn: 'Començar una subhasta'
        },
        activeListings: {
            title: 'Totes les subhastes',
            browseAll: 'Explorar totes',
            error: 'Error al carregar les subhastes. Funciona el backend?',
            emptyTitle: 'No hi ha subhastes encara',
            emptySub: 'Sigues el primer en crear una!',
            createBtn: 'Crear subhasta',
            colItem: 'Article',
            colSeller: 'Venedor',
            colStatus: 'Estat',
            colBid: 'Puja',
            statusLive: 'En directe',
            actionJoin: 'Unir-se',
            actionView: 'Veure'
        },
        profile: {
            title: 'El Meu Perfil',
            stats: 'Les Meves Estadístiques',
            activity: 'Activitat Recent',
            edit: 'Editar Perfil'
        },
        auctioneers: {
            title: 'Millors Subhastadors',
            subtitle: 'Descubreix els millors venedors.'
        },
        login: {
            liveBadge: 'Subhastes en directe ara',
            title1: 'La plataforma de subhastes',
            title2: 'més emocionant',
            title3: '',
            title4: 'del món.',
            subtitle: 'Mira, puja i guanya en temps real. Milers d\'articles en directe cada dia.',
            stat1: 'Subhastes actives',
            stat2: 'En directe ara',
            stat3: 'Satisfacció',
            welcome: 'Benvingut de nou',
            welcomeSub: 'Inicia sessió per continuar pujant',
            email: 'Correu electrònic',
            emailPlaceholder: 'tu@exemple.com',
            pass: 'Contrasenya',
            forgotPass: 'Has oblidat la contrasenya?',
            passPlaceholder: 'La teva contrasenya',
            btnSign: 'Iniciar sessió',
            or: 'O continuar amb',
            noAccount: 'No tens cap compte?',
            createOne: 'Crea\'n un'
        },
        register: {
            title1: 'Uneix-te a la plataforma de subhastes',
            title2: 'de més ràpid creixement',
            title3: '',
            subtitle: 'Compra, ven i puja per articles únics — en temps real. Crea el teu compte en segons.',
            stat1: 'Creació de compte',
            stat2: 'Experiència de pujes',
            stat3: 'Transaccions',
            create: 'Crea el teu compte',
            createSub: 'Comença a pujar en segons.',
            username: 'Nom d\'usuari',
            userPlaceholder: 'usuari99',
            email: 'Correu electrònic',
            emailPlaceholder: 'tu@exemple.com',
            pass: 'Contrasenya',
            passPlaceholder: 'Mín. 6 caràcters',
            confirm: 'Confirmar contrasenya',
            confirmPlaceholder: 'Repeteix la contrasenya',
            passMismatch: 'Les contrasenyes no coincideixen',
            btnCreate: 'Crear compte',
            or: 'O continuar amb',
            hasAccount: 'Ja tens un compte?',
            signIn: 'Inicia sessió'
        },
        search: {
            title1: 'Explorar ',
            title2: 'subhastes',
            searchPlaceholder: 'Cercar per nom...',
            searchBtn: 'Cercar',
            allBtn: 'Totes',
            searching: 'Cercant...',
            found: 'subhastes trobades',
            foundSingle: 'subhasta trobada',
            inCategory: 'en',
            forQuery: 'per a',
            clearAll: 'Esborrar filtres',
            error: 'No s\'han pogut carregar. Torna a intentar-ho.',
            noTitle: 'No s\'han trobat subhastes',
            noSubFiltered: 'No hi ha resultats per a aquests filtres.',
            noSubEmpty: 'Sigues el primer en crear una!',
            clearBtn: 'Esborrar filtres',
            createBtn: 'Crear subhasta'
        },
        create: {
            title: 'Nova subhasta',
            subtitle: 'Completa els detalls i comença en directe a l\'instant.',
            photo: 'Foto de l\'article',
            uploadText: 'Fes clic per pujar o arrossega i deixa anar',
            uploadSub: 'PNG, JPG o WEBP — màx 5MB',
            removeImg: 'Treure imatge',
            itemTitle: 'Títol *',
            titlePlaceholder: 'ex. Rolex Submariner Vintage 1965',
            desc: 'Descripció',
            descPlaceholder: 'Descriu el teu article — estat, autenticitat, història...',
            category: 'Categoria',
            price: 'Preu inicial *',
            launchBtn: 'Llançar subhasta en directe',
            launchSub: 'La teva subhasta començarà immediatament com un directe'
        },
        dashboard: {
            title: 'Tauler',
            welcome: 'Benvingut/da de nou,',
            newBtn: 'Nova subhasta',
            totalAuctions: 'Subhastes totals',
            liveNow: 'En directe ara',
            totalValue: 'Valor total',
            myAuctions: 'Les meves subhastes',
            colItem: 'Article',
            colStatus: 'Estat',
            colStarting: 'Inicial/Actual',
            colFinal: 'Preu final',
            colActions: 'Accions',
            noActive: 'No hi ha subhastes actives',
            createFirst: 'Crea la teva primera subhasta',
            badgeLive: 'En directe',
            badgeEnded: 'Finalitzada',
            badgeNotLive: 'Sense començar',
            btnEnterLive: 'Entrar al Directe',
            btnGoLive: 'Iniciar Directo',
            historyTitle: 'Historial de Pujes (Finalitzades)',
            noEnded: 'No hi ha subhastes finalitzades encara',
            badgeCompleted: 'Completada',
            btnClosed: 'Tancada'
        }
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('en'); // Default to English

    const t = (key) => {
        const keys = key.split('.');
        let value = translations[language];
        for (const k of keys) {
            value = value?.[k];
            if (!value) return key; // Fallback to key if not found
        }
        return value;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
